def printinfo( name="may", age=20 ):
  print ("Name: ", name)
  print ("Age:", age)
  print("-----------")
  return( )
printinfo('miki',50)
printinfo( )
printinfo("John")
printinfo(age=300)
printinfo('max',45)