import pandas as pd
fortune = pd.read_csv("fortune1000.csv",
                      index_col='Rank')
print(fortune)
sectors=fortune.groupby("Sector")
print(sectors.size())
print(sectors.get_group('Energy'))
print()
print(sectors.get_group('Energy').max())
print()
print(sectors.get_group('Energy').min())
print()
print(sectors.get_group('Energy')['Revenue'].median())
print(sectors.sum())
print()
print(sectors.mean())
print()
print(sectors.agg('sum'))
print()
print(sectors.agg(['size','sum','mean']))
print()
print(sectors.agg({'Revenue':['size','sum','mean']}))
print()
print(sectors.agg({"Revenue":["sum","mean"],"Employees":"mean"}))