import numpy as np
x = np.linspace(1,10,6).reshape((3,2))
print(x)
print("-----")
x = np.linspace(1,10,6).reshape((2,3))
print(x)
print("-----")
x =np.arange(8).reshape((2,4))
print(x)
print("-----")
x =np.arange(8).reshape((4,2))
print(x)
print("-----")
